# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # GitHub Actions (/.github/workflows/*.yml)
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
      time: '19:00'
      timezone: Asia/Tokyo
    commit-message:
      prefix: ci(gh-actions)
    milestone: 9
    labels:
      - 'dependabot :robot:'
    reviewers:
      - ddradar/developer

  # Devcontainer (/.devcontainer/*)
  - package-ecosystem: devcontainers
    directory: /
    schedule:
      interval: monthly
      time: '19:00'
      timezone: Asia/Tokyo
    commit-message:
      prefix: ci(devcontainer)
    milestone: 9
    labels:
      - 'dependabot :robot:'
    reviewers:
      - ddradar/developer

  # Node.js (/**/package.json)
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: monthly
      time: '18:00'
      timezone: Asia/Tokyo
    groups:
      vitest:
        dependency-type: development
        patterns:
          - '@vitest/*'
          - vitest
      iconify:
        patterns:
          - '@iconify-json/*'
      lint-tools:
        dependency-type: development
        patterns:
          - 'eslint*'
          - husky
          - lint-staged
          - prettier
        update-types: [minor, patch]
      nuxt:
        patterns:
          - '@nuxt/*'
          - 'nuxt'
        update-types: [minor, patch]
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope
    milestone: 9
    labels:
      - 'dependabot :robot:'
    reviewers:
      - ddradar/developer
    open-pull-requests-limit: 20
