# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # GitHub Actions (/.github/workflows/*.yml)
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
      time: '19:00'
      timezone: Asia/Tokyo
    cooldown:
      default-days: 5
    commit-message:
      prefix: ci(gh-actions)
    labels:
      - 'dependabot :robot:'

  # Devcontainer (/.devcontainer/*)
  - package-ecosystem: devcontainers
    directory: /
    schedule:
      interval: daily
      time: '19:00'
      timezone: Asia/Tokyo
    cooldown:
      default-days: 5
    commit-message:
      prefix: ci(devcontainer)
    labels:
      - 'dependabot :robot:'

  # Node.js(/**/package.json)
  - package-ecosystem: npm
    directories:
      - /
    schedule:
      interval: daily
      time: '18:00'
      timezone: Asia/Tokyo
    cooldown:
      default-days: 5
      semver-major-days: 30
      semver-minor-days: 7
      semver-patch-days: 3
    groups:
      iconify:
        patterns:
          - '@iconify-json/*'
      nuxt:
        patterns:
          - '@nuxt/*'
          - 'nuxt'
        update-types: [minor, patch]
      vitest:
        dependency-type: development
        patterns:
          - '@vitest/*'
          - vitest
      lint-tools:
        dependency-type: development
        patterns:
          - 'eslint*'
          - husky
          - lint-staged
          - prettier
        update-types: [minor, patch]
    ignore:
      # Should match the runtime Node.js major version, so keep it manually updated.
      - dependency-name: '@types/node'
        update-types:
          - version-update:semver-major
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope
    labels:
      - 'dependabot :robot:'
    open-pull-requests-limit: 20
