// Generated by nuxt-swa
declare module '#app' {
  interface PageMeta {
    /** List of roles required to view this page */
    allowedRoles?:
      | Exclude<UserRole, 'anonymous'>
      | Exclude<UserRole, 'anonymous'>[]
  }
}

export {}
