name: Node.js CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    name: Lint & Format Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Use pnpm ${{ vars.PNPM_VERSION }}
        uses: pnpm/action-setup@v2.4.0
        with:
          version: ${{ vars.PNPM_VERSION }}
      - name: Use Node.js ${{ vars.NODE_VERSION }}
        uses: actions/setup-node@v4.0.1
        with:
          node-version: ${{ vars.NODE_VERSION }}
          cache: pnpm

      - name: Install Project Dependencies
        run: pnpm install --frozen-lockfile --ignore-scripts

      - name: ESLint
        run: pnpm lint:eslint
      - name: Prettier
        run: pnpm lint:prettier

  test:
    name: Unit Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Use pnpm ${{ vars.PNPM_VERSION }}
        uses: pnpm/action-setup@v2.4.0
        with:
          version: ${{ vars.PNPM_VERSION }}
      - name: Use Node.js ${{ vars.NODE_VERSION }}
        uses: actions/setup-node@v4.0.1
        with:
          node-version: ${{ vars.NODE_VERSION }}
          cache: pnpm

      - name: Install Project Dependencies
        run: pnpm install --frozen-lockfile

      - name: Test
        run: pnpm test

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        env:
          token: ${{ secrets.CODECOV_TOKEN }}
